### PR TITLE
Trim exception stack trace if serialized message length is too long

### LINKED ISSUE #2: Remove flattened exception for failure_transport
After the message failed to be sent it will be moved to the failure_transport queue.
Unfortunatelly Azure Storage doesn't allow the message to be bigger than 48 kb.
We will have to remove the exception trace before saving the message into Azure Queues.
Maybe provide an option?

### PR DESCRIPTION
**Pull request by SpartakusMd**
Fixes #2

I see benefits in keeping the flattened exception with the previous exception for debug purposes. Due to this I didn't remove the flattened exception but limited the stack trace in the exceptions to 5 elements.

### CODE REVIEW

File: src/EventListener/MaxMessageFailedSizeListener.php [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+            return $stamp;
+        }
+
+        $this->cleanupStackTrace($previous);
+        $previous->setPrevious(null);
+
+        return $stamp;
+    }
+
+    private function cleanupStackTrace(FlattenException $flattenException): void
```
Comment (alexandrubau) [inline src/EventListener/MaxMessageFailedSizeListener.php:107]: You should add missing PHPDoc block comments to all methods in order to be consistent.

**Review by alexandrubau — CHANGES_REQUESTED** [review]
Pull request looks great! Just a small comment regarding PHPDoc comments.

File: src/EventListener/MaxMessageFailedSizeListener.php (hunk 1 above)
Comment (SpartakusMd) [reply src/EventListener/MaxMessageFailedSizeListener.php:107]: Old habit to remove them. Added the missing ones.

**Review by alexandrubau — APPROVED** [review]

**Comment by alexandrubau** [comment]
Amazing job @SpartakusMd ! 🎉 Please let me know if you can merge this by yourself.

**Comment by SpartakusMd** [comment]
Yes, I can. Waited for your approval.

I will merge and release it as 1.3.1
